#!/usr/bin/env bash
# This script creates a PID file, handles signals, and removes the PID file on exit
echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
