#!/bin/bash
# 11-manage_my_process
# Description: Init script to manage manage_my_process

PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="$(pwd)/manage_my_process"

case "$1" in
    start)
        $SCRIPT_PATH &
        echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE) 2>/dev/null
            rm -f $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE) 2>/dev/null
            rm -f $PID_FILE
        fi
        $SCRIPT_PATH &
        echo $! > $PID_FILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
