#!/usr/bin/env bash
# This script stops 4-to_infinity_and_beyond process without using kill or killal
for pid in $(ps aux | grep '[4]-to_infinity_and_beyond' | awk '{print $2}'); do
    echo -n > /proc/$pid/fd/1
done

